name: app-dev

services:
  frontend:
    build:
      context: ./todo-web
      dockerfile: dev.Dockerfile
    develop:
      watch:
        - action: sync
          path: ./todo-web
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./todo-web/package.json
              
  backend:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - out/
  valkey:
    image: valkey/valkey:7.2.5-alpine
    restart: unless-stopped

  caddy:
    image: caddy/caddy:2.8-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile.dev:/etc/caddy/Caddyfile
