name: app

services:
  backend:
    image: backend/backend:latest
    depends_on: 
      - valkey
  valkey:
    image: valkey/valkey:7.2.5-alpine
    restart: unless-stopped

  caddy:
    image: caddy/caddy:2.8-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/dist:/var/www/html
