services:
  frontend:
    build:
      context: ./todo-web
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./todo-web
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./todo-web/package.json
              
  backend:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
          ignore:
            - out/
  valkey:
    image: valkey/valkey:7.2.5-alpine
    restart: unless-stopped
